# Generated by Django 5.0.7 on 2024-07-18 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('breed', models.CharField(max_length=50, unique=True)),
                ('age', models.IntegerField()),
                ('color', models.CharField(max_length=32, unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='img/')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filler', models.CharField(max_length=16, unique=True)),
                ('carrier', models.CharField(max_length=16, unique=True)),
                ('feed', models.CharField(choices=[('Сухой корм', 'Сухой корм'), ('Жидкий корм', 'Жидкий корм')], max_length=50)),
            ],
        ),
    ]
