# Generated by Django 5.0.7 on 2024-07-18 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zootovar', '0002_cat_description_en_cat_description_ru_cat_name_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='age',
            field=models.IntegerField(verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='breed',
            field=models.CharField(max_length=50, unique=True, verbose_name='Порода'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='color',
            field=models.CharField(max_length=32, unique=True, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='description',
            field=models.TextField(verbose_name='Описания'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описания'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описания'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='name_en',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='name_ru',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='img/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='product',
            name='carrier',
            field=models.CharField(max_length=16, unique=True, verbose_name='Переноска'),
        ),
        migrations.AlterField(
            model_name='product',
            name='carrier_en',
            field=models.CharField(max_length=16, null=True, unique=True, verbose_name='Переноска'),
        ),
        migrations.AlterField(
            model_name='product',
            name='carrier_ru',
            field=models.CharField(max_length=16, null=True, unique=True, verbose_name='Переноска'),
        ),
        migrations.AlterField(
            model_name='product',
            name='feed',
            field=models.CharField(choices=[('Сухой корм', 'Сухой корм'), ('Жидкий корм', 'Жидкий корм')], max_length=50, verbose_name='Корм'),
        ),
        migrations.AlterField(
            model_name='product',
            name='filler',
            field=models.CharField(max_length=16, unique=True, verbose_name='Наполнитель'),
        ),
        migrations.AlterField(
            model_name='product',
            name='filler_en',
            field=models.CharField(max_length=16, null=True, unique=True, verbose_name='Наполнитель'),
        ),
        migrations.AlterField(
            model_name='product',
            name='filler_ru',
            field=models.CharField(max_length=16, null=True, unique=True, verbose_name='Наполнитель'),
        ),
    ]
